Update function 3
Lesego-Shange/Shashercise2 pull request #2
Opened 2024-03-26 08:55 UTC by PBaloyi449

2024-03-26 08:55 UTC, PBaloyi449 commented
Updating the third function

2024-03-27 05:05 UTC, Lesego-Shange requested changes
Please make the changes as requested then resubmit

2024-03-27 05:05 UTC, Lesego-Shange commented on index.js
> +let state = 'idle';
No changing above line

2024-03-27 05:05 UTC, Lesego-Shange commented on index.js
> -  if (calculated > 3) state = 'idle'
Do not delete other code

2024-03-27 05:05 UTC, Lesego-Shange commented on index.js
> +const checkUser = () => {
Please perform fetch then retry the commit

2024-03-27 07:15 UTC, closed without merging